const fs = require("fs");
const path = require("path");
const { html_to_pdf } = require(".");
try {
  (async () => {
    // Enhanced Invoice

    // const dataBinding = {
    //     boxes: [
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //     ],
    //     invoice_number: "uwediufi7u3w4",
    //     date: '17/23/2022',
    //     payment_terms_label: "Due On Receipt",
    //     due_date: "23/12/2022",
    //     reference_number: 38495743584,
    //     payment_mode: "Cash",
    //     place_of_supply: "MH",
    //     table_heading: [
    //         { name: "#" },
    //         { name: "Image" },
    //         { name: "Item Name, SKU & Brand" },
    //         { name: "HSN/SAC" },
    //         { name: "EAN" },
    //         { name: "Qty" },
    //         { name: "Rate" },
    //         { name: "IGST" },
    //         { name: "IGST Rate" },
    //         { name: "Amount" },
    //     ],
    //     supplier_details: {
    //         supplier_name: "Merhaki Foods and Nutrition Private Limited",
    //         gst_no: "27AABCR1718E1ZP",
    //         billing_address: {
    //             street: " 3rd, 4th Floor, 9/1. 9th Main, Sector 6, HSR Layout, HSR Layout,Bengaluru (Bangalore) Urban, Karnataka 560102, India,",
    //             city: "Maharashtra",
    //             country: "India",
    //         },
    //     },
    //     customer_details: {
    //         billing_address: {
    //             name: "Reliance Retail Limited",
    //             street: " CTS no F 1079 Plot no 86 1st 2nd 3rd and 4th Floor,",
    //             city: "Maharashtra",
    //             country: "India",
    //             gst_no: "27AABCR1718E1ZP",
    //         },
    //         shipping_address: {
    //             name: "Reliance Retail Limited",
    //             street: " CTS no F 1079 Plot no 86 1st 2nd 3rd and 4th Floor,",
    //             city: "Maharashtra",
    //             country: "India",
    //             gst_no: "27AABCR1718E1ZP",
    //         },
    //     },
    //     transporter: {
    //         name: "XpressBess",
    //         vehicle_number: "Up14 BM0567",
    //         dispatch_number: "98765432168",
    //         eway_bill: "721318345301",
    //         box_number: 100,
    //         shipment_weight: "1000Kg",
    //     },
    //     hsn_or_sac: true,
    //     igst_rate: true,
    //     igst: true,
    //     rate:true,
    //     items: [
    //         {
    //             index: 1,
    //             img_url:
    //                 "https://molly-prod.s3.ap-south-1.amazonaws.com/1668479250897_Teal.png",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             ean: "8904387252224",
    //             hsn_or_sac: 71171990,
    //             quantity: 321,
    //             rate: 76523,
    //             type: "HSN/SAC",
    //             igst_rate: "33.3",
    //             igst: 1703,
    //             item_total: 25000,
    //         },
    //         {
    //             index: 2,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             rate: 5345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 3,
    //             img_url:
    //                 "https://molly-prod.s3.ap-south-1.amazonaws.com/1668479250897_Teal.png",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             rate: 5345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 4,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             rate: 5345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 5,
    //             img_url:
    //                 "https://molly-prod.s3.ap-south-1.amazonaws.com/1668479250897_Teal.png",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             rate: 5345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 6,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             rate: 5345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //     ],
    //     sub_total: 252324.89,
    //     tax_total: 7364.78,
    //     shipping_charges: 87544.53,
    //     total: 2834732.34,
    //     balance_due: 837.54,
    //     total_quantity: 3212.0,
    //     irn_img:
    //         "https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.techinasia.com%2Fwp-content%2Fuploads%2F2010%2F11%2Fqrcode1.png&tbnid=jnM6dFH6ov1GAM&vet=12ahUKEwjSmOPEyqT_AhU223MBHaEACVgQMygMegUIARCDAg..i&imgrefurl=https%3A%2F%2Fwww.techinasia.com%2Fqr-codes-social-marketing-2&docid=nui7L0bKf6IdrM&w=234&h=234&q=random%20qr%20image&ved=2ahUKEwjSmOPEyqT_AhU223MBHaEACVgQMygMegUIARCDAg",
    //     irn: "83517da0b7acdec370e8eeb27fe31dfe3921884916ebbb6c0ac16813cd793ca5",
    //     ack_no: "112315087713663",
    //     ack_date: "2023-01-16 10:50:00",
    //     total_amount_in_words:
    //         "Indian Rupee Three Hundred Twelve and Twelve Paise Only.",
    //     total: 600,
    //     notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a mauris at nulla pretium hendrerit. Mauris erat neque, vehicula at cursus eget, eleifend ac purus",
    //     terms: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a mauris at nulla pretium hendrerit. Mauris erat neque, vehicula at cursus eget, eleifend ac purus",
    // };

    // Performa Invoice

    // const dataBinding = {
    //     order_number: "3894hjf3984y",
    //     order_date: "17/23/2022",
    //     payment_terms_label: "Due On Receipt",
    //     due_date: "23/12/2022",
    //     reference_number: 38495743584,
    //     payment_mode: "Cash",
    //     place_of_supply: "MH",
    //     table_heading: [
    //         { name: "#" },
    //         { name: "Image" },
    //         { name: "Item Name, SKU & Brand" },
    //         { name: "HSN/SAC" },
    //         { name: "EAN" },
    //         { name: "Qty" },
    //         { name: "Rate" },
    //         { name: "IGST" },
    //         { name: "IGST Rate" },
    //         { name: "Amount" },
    //     ],
    //     supplier_details: {
    //         supplier_name: "Merhaki Foods and Nutrition Private Limited",
    //         gst_no: "27AABCR1718E1ZP",
    //         billing_address: {
    //             street: " 3rd, 4th Floor, 9/1. 9th Main, Sector 6, HSR Layout, HSR Layout,Bengaluru (Bangalore) Urban, Karnataka 560102, India,",
    //             city: "Maharashtra",
    //             country: "India",
    //         },
    //     },
    //     customer_details: {
    //         billing_address: {
    //             name: "Reliance Retail Limited",
    //             street: " CTS no F 1079 Plot no 86 1st 2nd 3rd and 4th Floor,",
    //             city: "Maharashtra",
    //             country: "India",
    //             gst_no: "27AABCR1718E1ZP",
    //         },
    //         shipping_address: {
    //             name: "Reliance Retail Limited",
    //             street: " CTS no F 1079 Plot no 86 1st 2nd 3rd and 4th Floor,",
    //             city: "Maharashtra",
    //             country: "India",
    //             gst_no: "27AABCR1718E1ZP",
    //         },
    //     },
    //     // transporter: {
    //     //     name: "XpressBess",
    //     //     vehicle_number: "Up14 BM0567",
    //     //     dispatch_number: "98765432168",
    //     //     eway_bill: "721318345301",
    //     //     box_number: 100,
    //     //     shipment_weight: "1000Kg",
    //     // },
    //     hsn_or_sac: true,
    //     igst: true,
    //     igst_rate: true,
    //     items: [
    //         {
    //             index: 1,
    //             img_url:
    //                 "https://molly-prod.s3.ap-south-1.amazonaws.com/1668479250897_Teal.png",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             ean: "8904387252224",
    //             hsn_or_sac: 71171990,
    //             quantity: 321,
    //             type: "HSN/SAC",
    //             igst_rate: "igstR",
    //             igst: 'igst',
    //             item_total: 'iTotal',
    //         },
    //         {
    //             index: 2,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 3,
    //             img_url:
    //                 "https://molly-prod.s3.ap-south-1.amazonaws.com/1668479250897_Teal.png",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 4,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 5,
    //             img_url:
    //                 "https://molly-prod.s3.ap-south-1.amazonaws.com/1668479250897_Teal.png",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 6,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //     ],
    //     sub_total: 252324.89,
    //     tax_total: 7364.78,
    //     shipping_charges: 87544.53,
    //     total: 2834732.34,
    //     balance_due: 837.54,
    //     total_quantity: 3212.0,
    //     irn_img:
    //         "https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.techinasia.com%2Fwp-content%2Fuploads%2F2010%2F11%2Fqrcode1.png&tbnid=jnM6dFH6ov1GAM&vet=12ahUKEwjSmOPEyqT_AhU223MBHaEACVgQMygMegUIARCDAg..i&imgrefurl=https%3A%2F%2Fwww.techinasia.com%2Fqr-codes-social-marketing-2&docid=nui7L0bKf6IdrM&w=234&h=234&q=random%20qr%20image&ved=2ahUKEwjSmOPEyqT_AhU223MBHaEACVgQMygMegUIARCDAg",
    //     irn: "83517da0b7acdec370e8eeb27fe31dfe3921884916ebbb6c0ac16813cd793ca5",
    //     ack_no: "112315087713663",
    //     ack_date: "2023-01-16 10:50:00",
    //     total_amount_in_words:
    //         "Indian Rupee Three Hundred Twelve and Twelve Paise Only.",
    //     total: 600,
    //     notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a mauris at nulla pretium hendrerit. Mauris erat neque, vehicula at cursus eget, eleifend ac purus",
    //     terms: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a mauris at nulla pretium hendrerit. Mauris erat neque, vehicula at cursus eget, eleifend ac purus",
    //     isWatermark: true,
    // };

    // Invoice tax

    // const dataBinding = {
    //   invoice_number: "MFN/PB24-25/0383",
    //   isB2B2B: true,
    //   date: "2024-05-22",
    //   due_date: "2024-06-06",
    //   payment_terms_label: "Net 15",
    //   payment_mode: "",
    //   place_of_supply: "TN",
    //   reference_number: "GBIZ323151, GBIZ323152",
    //   terms: "test123",
    //   payment_terms: "",
    //   notes: "test123",
    //   supplier_details: {
    //     supplier_name: "BUTTERNUT VENTURES",
    //     gst_no: "27AAJCB2594G1ZH",
    //     billing_address: {
    //       street:
    //         "Plot no F-38, Additional Ambernath Industrial Area, Anand Nagar MIDC, Ambernath(E)",
    //       city: "Mumbai",
    //       state: "Maharashtra",
    //       country: "India",
    //       zip: "421506",
    //     },
    //   },
    //   dispatch_address: {
    //     name: "Merhaki Foods And Nutrition Private Limited",
    //     street: "Malerkotla Road, Village Kaind, ",
    //     street2: "Ludhiana, Punjab, 141116",
    //     city: "Ludhiana",
    //     state: "Punjab",
    //     country: "India",
    //     zip: "141116",
    //     gst_no: "03AALCM3577E1ZH",
    //     contact_number: "",
    //   },
    //   customer_details: {
    //     billing_address: {
    //       name: "Nykaa E-Retail",
    //       street: "Value Space Logistics & Industrial Park Pvt Ltd",
    //       street2: "CCI Logistics Warehouse No.3,SH-57 Village No.104",
    //       city: "Tiruvallur",
    //       state: "Tamil Nadu",
    //       country: "India",
    //       zip: "602002",
    //       gst_no: "33AAFCN5072P1Z2",
    //       contact_number: "",
    //     },
    //     shipping_address: {
    //       name: "Nykaa E-Retail",
    //       street: "Value Space Logistics & Industrial Park Pvt Ltd",
    //       street2: "CCI Logistics Warehouse No.3,SH-57 Village No.104",
    //       city: "Tiruvallur",
    //       state: "Tamil Nadu",
    //       country: "India",
    //       zip: "602002",
    //       gst_no: "33AAFCN5072P1Z2",
    //       contact_number: "",
    //     },
    //   },
    //   items: [
    //     {
    //       index: 1,
    //       name: "Kuber IndustriesArtificial Plant  225082",
    //       sku: "2000000124264",
    //       tag_name: "Kuber International",
    //       hsn_or_sac: "67029090",
    //       ean: "8905721102236",
    //       quantity: 10,
    //       discount_percentage: "99.83%",
    //       rate: 1,
    //       igst_rate: 18,
    //       igst: 1.8,
    //       item_total: 10,
    //     },
    //     {
    //       index: 2,
    //       name: "Yellow Chimes Jewellery SetYCADNS295DESCRYWH",
    //       sku: "2000000130125",
    //       tag_name: "Yellow Chimes",
    //       hsn_or_sac: "71171990",
    //       ean: "8904387291704",
    //       quantity: 10,
    //       discount_percentage: "99.99%",
    //       rate: 1,
    //       igst_rate: 3,
    //       igst: 0.3,
    //       item_total: 10,
    //     },
    //     {
    //       index: 3,
    //       name: "Yellow Chimes Jewellery SetYCADNS299CRYDRPPK",
    //       sku: "2000000130115",
    //       tag_name: "Yellow Chimes",
    //       hsn_or_sac: "71171990",
    //       ean: "8904387291803",
    //       quantity: 10,
    //       discount_percentage: "99.98%",
    //       rate: 1,
    //       igst_rate: 3,
    //       igst: 0.3,
    //       item_total: 10,
    //     },
    //     {
    //       index: 4,
    //       name: "(TCFBPPO-GA-30LLTBU2)-  The Clownfish  Kids Backpack   -(Scholastic Light..",
    //       sku: "2000000127295",
    //       tag_name: "Clownfish",
    //       hsn_or_sac: "42021250",
    //       ean: "8903606628208",
    //       quantity: 9,
    //       discount_percentage: "99.97%",
    //       rate: 1,
    //       igst_rate: 18,
    //       igst: 1.62,
    //       item_total: 9,
    //     },
    //     {
    //       index: 5,
    //       name: "Yellow Chimes Jewellery SetYCADNS292DRPLEFRG",
    //       sku: "2000000130134",
    //       tag_name: "Yellow Chimes",
    //       hsn_or_sac: "71171990",
    //       ean: "8904387291629",
    //       quantity: 9,
    //       discount_percentage: "99.98%",
    //       rate: 1,
    //       igst_rate: 3,
    //       igst: 0.27,
    //       item_total: 9,
    //     },
    //     {
    //       index: 6,
    //       name: "Reach T90 PT Manual Treadmill for Home Workout | Foldable Treadmill With Wheels | Walking  Running Machine For Home Gym | Manual Incline |",
    //       sku: "2000000127349",
    //       tag_name: "Reach",
    //       hsn_or_sac: "950691",
    //       ean: "8905721093497",
    //       quantity: 6,
    //       discount_percentage: "100%",
    //       rate: 1,
    //       igst_rate: 18,
    //       igst: 1.08,
    //       item_total: 6,
    //     },
    //     {
    //       index: 7,
    //       name: "Kuber IndustriesArtificial Plant  20220201",
    //       sku: "2000000124275",
    //       tag_name: "Kuber International",
    //       hsn_or_sac: "67029090",
    //       ean: "8905721102342",
    //       quantity: 8,
    //       discount_percentage: "99.8%",
    //       rate: 1,
    //       igst_rate: 18,
    //       igst: 1.44,
    //       item_total: 8,
    //     },
    //     {
    //       index: 8,
    //       name: "Kuber IndustriesArtificial Plant  20220193",
    //       sku: "2000000124276",
    //       tag_name: "Kuber International",
    //       hsn_or_sac: "67029090",
    //       ean: "8905721102359",
    //       quantity: 10,
    //       discount_percentage: "99.86%",
    //       rate: 1,
    //       igst_rate: 18,
    //       igst: 1.8,
    //       item_total: 10,
    //     },
    //   ],
    //   boxes: [{ length: 10, breadth: 10, height: 10, boxes: 1, suffix: "" }],
    //   transporter: {
    //     name: "",
    //     vehicle_number: "",
    //     dispatch_number: "",
    //     eway_bill: "",
    //     box_number: 1,
    //     shipment_weight: "10 kg",
    //   },
    //   total_quantity: 72,
    //   total_amount_in_words: "Eighty Rupees and Sixty One Paise only.",
    //   sub_total: "72",
    //   tax_total: "8.61",
    //   total: "80.61",
    //   balance_due: "80.61",
    //   irn_img: "",
    //   irn: "",
    //   ack_no: "",
    //   ack_date: "",
    //   show_discount: true,
    //   vendorSignature:
    //     "https://dev-molly-uploads.s3.ap-south-1.amazonaws.com/merhaki_sign.png",
    // };

    const dataBinding = {
      invoice_number: "MFN/PB24-25/0382",
      isB2B2B: true,
      date: "2024-05-22",
      due_date: "2024-06-06",
      payment_terms_label: "Net 15",
      payment_mode: "",
      place_of_supply: "TN",
      reference_number: "GBIZ323151, GBIZ323152",
      terms: "test123",
      payment_terms: "",
      notes: "test123",
      supplier_details: {
        supplier_name: "Merhaki Foods And Nutrition Private Limited",
        gst_no: "03AALCM3577E1ZH",
        billing_address: {
          street:
            "Malerkotla Road, Village Kaind, , Ludhiana, Punjab, 141116, Ludhiana, Punjab, 141116, Malerkotla Road, Village Kaind, , Ludhiana, Punjab, 141116, Ludhiana, Punjab, 141116",
          city: "Ludhiana",
          state: "Punjab",
          country: "India",
          zip: "141116",
        },
      },
      dispatch_address: {
        name: "Merhaki Foods And Nutrition Private Limited",
        street: "SECOND FLOOR , UNIT NO.202,",
        street2: "SECTOR 20A, EF3 MALL,",
        city: "FARIDABAD",
        state: "Haryana",
        country: "India",
        zip: "121001",
        gst_no: "06AALCM3577E1ZB",
        contact_number: "",
      },
      customer_details: {
        billing_address: {
          name: "Nykaa E-Retail",
          street: "Value Space Logistics & Industrial Park Pvt Ltd",
          street2: "CCI Logistics Warehouse No.3,SH-57 Village No.104",
          city: "Tiruvallur",
          state: "Tamil Nadu",
          country: "India",
          zip: "602002",
          gst_no: "33AAFCN5072P1Z2",
          contact_number: "",
        },
        shipping_address: {
          name: "Nykaa E-Retail",
          street: "Value Space Logistics & Industrial Park Pvt Ltd",
          street2: "CCI Logistics Warehouse No.3,SH-57 Village No.104",
          city: "Tiruvallur",
          state: "Tamil Nadu",
          country: "India",
          zip: "602002",
          gst_no: "33AAFCN5072P1Z2",
          contact_number: "",
        },
      },
      items: [
        {
          index: 1,
          name: "SAVYA HOME Apollo ADJ ARMREST Set Without PU PAD",
          sku: "2000000101006",
          tag_name: "Savya Homes",
          hsn_or_sac: "940310",
          ean: "8905721111764",
          quantity: 7,
          discount_percentage: "99.96%",
          rate: 1,
          igst_rate: 18,
          igst: 1.26,
          item_total: 7,
        },
      ],
      boxes: [{ length: 10, breadth: 10, height: 10, boxes: 1, suffix: "" }],
      transporter: {
        name: "",
        vehicle_number: "",
        dispatch_number: "",
        eway_bill: "",
        box_number: 1,
        shipment_weight: "10 kg",
      },
      total_quantity: 7,
      total_amount_in_words: "Eight Rupees and Twenty Six Paise only.",
      sub_total: "7",
      tax_total: "1.26",
      total: "8.26",
      balance_due: "8.26",
      irn_img: "",
      irn: "",
      ack_no: "",
      ack_date: "",
      show_discount: true,
      vendorSignature:
        "https://dev-molly-uploads.s3.ap-south-1.amazonaws.com/merhaki_sign.png",
    };

    // const dataBinding = {
    //     boxes: [
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //         { boxes: 999, length: 131, breadth: 654, height: 827 },
    //     ],
    //     invoice_number: "MF/MH24-25/01567",
    //     date: '17/23/2022',
    //     payment_terms_label: "Due On Receipt",
    //     payment_terms: "Due On Receipt",
    //     due_date: "23/12/2022",
    //     reference_number: 38495743584,
    //     payment_mode: "Cash",
    //     place_of_supply: "MH",
    //     table_heading: [
    //         { name: "#" },
    //         { name: "Image" },
    //         { name: "Item Name, SKU & Brand" },
    //         { name: "HSN/SAC" },
    //         { name: "EAN" },
    //         { name: "Qty" },
    //         { name: "Rate" },
    //         { name: "IGST" },
    //         { name: "IGST Rate" },
    //         { name: "Amount" },
    //     ],
    //     supplier_details: {
    //         supplier_name: "Merhaki Foods and Nutrition Private Limited",
    //         gst_no: "27AABCR1718E1ZP",
    //         billing_address: {
    //             street: " 3rd, 4th Floor, 9/1. 9th Main, Sector 6, HSR Layout, HSR Layout,Bengaluru (Bangalore) Urban, Karnataka 560102, India,",
    //             city: "Maharashtra",
    //             country: "India",
    //         },
    //     },
    //     customer_details: {
    //         billing_address: {
    //             name: "Reliance Retail Limited",
    //             street: " CTS no F 1079 Plot no 86 1st 2nd 3rd and 4th Floor,",
    //             city: "Maharashtra",
    //             country: "India",
    //             gst_no: "27AABCR1718E1ZP",
    //         },
    //         shipping_address: {
    //             name: "Reliance Retail Limited",
    //             street: " CTS no F 1079 Plot no 86 1st 2nd 3rd and 4th Floor,",
    //             city: "Maharashtra",
    //             country: "India",
    //             gst_no: "27AABCR1718E1ZP",
    //         },
    //     },
    //     dispatch_address: {
    //         name: "Reliance Retail Limited",
    //         street: " CTS no F 1079 Plot no 86 1st 2nd 3rd and 4th Floor,",
    //         city: "Maharashtra",
    //         country: "India",
    //         gst_no: "27AABCR1718E1ZP",
    //     },
    //     transporter: {
    //         name: "XpressBess",
    //         vehicle_number: "Up14 BM0567",
    //         dispatch_number: "98765432168",
    //         eway_bill: "721318345301",
    //         box_number: 100,
    //         shipment_weight: "1000Kg",
    //     },
    //     hsn_or_sac: true,
    //     igst_rate: true,
    //     igst: true,
    //     rate:true,
    //     isB2B2B: false,
    //     isB2B: false,
    //     items: [
    //         {
    //             index: 1,
    //             img_url:
    //                 "https://molly-prod.s3.ap-south-1.amazonaws.com/1668479250897_Teal.png",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             ean: "8904387252224",
    //             hsn_or_sac: 71171990,
    //             quantity: 321,
    //             rate: 76523,
    //             type: "HSN/SAC",
    //             igst_rate: "33.3",
    //             igst: 1703,
    //             item_total: 25000,
    //         },
    //         {
    //             index: 2,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             rate: 5345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 3,
    //             img_url:
    //                 "https://molly-prod.s3.ap-south-1.amazonaws.com/1668479250897_Teal.png",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             rate: 5345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 4,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             rate: 5345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 5,
    //             img_url:
    //                 "https://molly-prod.s3.ap-south-1.amazonaws.com/1668479250897_Teal.png",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             rate: 5345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 6,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             rate: 5345,
    //             igst_rate: "99.3",
    //             igst: 2342,
    //             item_total: 23423,
    //         },
    //     ],
    //     sub_total: 252324.89,
    //     tax_total: 7364.78,
    //     shipping_charges: 87544.53,
    //     total: 2834732.34,
    //     balance_due: 837.54,
    //     total_quantity: 3212.0,
    //     irn_img:
    //         "https://www.google.com/imgres?imgurl=https%3A%2F%2Fcdn.techinasia.com%2Fwp-content%2Fuploads%2F2010%2F11%2Fqrcode1.png&tbnid=jnM6dFH6ov1GAM&vet=12ahUKEwjSmOPEyqT_AhU223MBHaEACVgQMygMegUIARCDAg..i&imgrefurl=https%3A%2F%2Fwww.techinasia.com%2Fqr-codes-social-marketing-2&docid=nui7L0bKf6IdrM&w=234&h=234&q=random%20qr%20image&ved=2ahUKEwjSmOPEyqT_AhU223MBHaEACVgQMygMegUIARCDAg",
    //     irn: "83517da0b7acdec370e8eeb27fe31dfe3921884916ebbb6c0ac16813cd793ca5",
    //     ack_no: "112315087713663",
    //     ack_date: "2023-01-16 10:50:00",
    //     total_amount_in_words:
    //         "Indian Rupee Three Hundred Twelve and Twelve Paise Only.",
    //     total: 600,
    //     notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a mauris at nulla pretium hendrerit. Mauris erat neque, vehicula at cursus eget, eleifend ac purus",
    //     terms: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a mauris at nulla pretium hendrerit. Mauris erat neque, vehicula at cursus eget, eleifend ac purus",
    // };
    console.log(dataBinding);
    // Purchase Order

    // const dataBinding = {
    //     po_number: "hf2938yr29d3982",
    //     po_date: "14/07/2022",
    //     payment_terms_label: "Due On Receipt",
    //     delivery_date: "23/12/2022",
    //     reference_number: 38495743584,
    //     table_heading: [
    //         { name: "#" },
    //         { name: "Image" },
    //         { name: "Item Name, SKU & Brand" },
    //         { name: "HSN/SAC" },
    //         { name: "EAN" },
    //         { name: "Qty" },
    //         { name: "Rate" },
    //         { name: "IGST" },
    //         { name: "IGST Rate" },
    //         { name: "Amount" },
    //     ],
    //     supplier_details: {
    //         supplier_name: "Merhaki Foods and Nutrition Private Limited",
    //         gst_no: "27AABCR1718E1ZP",
    //         billing_address: {
    //             street: " 3rd, 4th Floor, 9/1. 9th Main, Sector 6, HSR Layout, HSR Layout,Bengaluru (Bangalore) Urban, Karnataka 560102, India,",
    //             city: "Maharashtra",
    //             country: "India",
    //         },
    //     },
    //     vendor_details: {
    //         billing_address: {
    //             name: "Reliance Retail Limited",
    //             street: " CTS no F 1079 Plot no 86 1st 2nd 3rd and 4th Floor,",
    //             city: "Maharashtra",
    //             country: "India",
    //             gst_no: "27AABCR1718E1ZP",
    //         },
    //         shipping_address: {
    //             name: "Reliance Retail Limited",
    //             street: " CTS no F 1079 Plot no 86 1st 2nd 3rd and 4th Floor,",
    //             city: "Maharashtra",
    //             country: "India",
    //             gst_no: "27AABCR1718E1ZP",
    //         },
    //     },
    //     // transporter: {
    //     //     name: "XpressBess",
    //     //     vehicle_number: "Up14 BM0567",
    //     //     dispatch_number: "98765432168",
    //     //     eway_bill: "721318345301",
    //     //     box_number: 100,
    //     //     shipment_weight: "1000Kg",
    //     // },
    //     hsn_or_sac: true,
    //     cgst_rate: true,
    //     gst: true,
    //     mrp: true,
    //     sgst_rate: true,
    //     purchase_price: true,
    //     items: [
    //         {
    //             index: 1,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             mrp: 5345,
    //             cgst_rate: "24.6%",
    //             sgst_rate: "30.4%",
    //             gst: "234",
    //             purchase_price: 82374,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 2,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             mrp: 5345,
    //             cgst_rate: "24.6%",
    //             sgst_rate: "30.4%",
    //             gst: "234",
    //             purchase_price: 82374,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 3,
    //             img_url:
    //                 "https://molly-prod.s3.ap-south-1.amazonaws.com/1668479250897_Teal.png",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             mrp: 5345,
    //             cgst_rate: "24.6%",
    //             sgst_rate: "30.4%",
    //             gst: "234",
    //             purchase_price: 82374,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 4,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             mrp: 5345,
    //             cgst_rate: "24.6%",
    //             sgst_rate: "30.4%",
    //             gst: "234",
    //             purchase_price: 82374,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 5,
    //             img_url:
    //                 "https://molly-prod.s3.ap-south-1.amazonaws.com/1668479250897_Teal.png",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             mrp: 5345,
    //             cgst_rate: "24.6%",
    //             sgst_rate: "30.4%",
    //             gst: "234",
    //             purchase_price: 82374,
    //             item_total: 23423,
    //         },
    //         {
    //             index: 6,
    //             img_url:
    //                 "https://d3zr9vspdnjxi.cloudfront.net/artistInfo/thomvint/thumb/609.jpg?0",
    //             name: "Yellow Chimes Earrings (YCFJER- 05HOPDNG-GL)1000000053112 Yellow Chimes",
    //             sku: "71171990",
    //             hsn_or_sac: 71171990,
    //             ean: "8904387252224",
    //             quantity: 345,
    //             mrp: 5345,
    //             cgst_rate: "24.6%",
    //             sgst_rate: "30.4%",
    //             gst: "234",
    //             purchase_price: 82374,
    //             item_total: 23423,
    //         },
    //     ],
    //     sub_total: 252324.89,
    //     tax_total: 7364.78,
    //     shipping_charges: 87544.53,
    //     total: 2834732.34,
    //     balance_due: 837.54,
    //     total_quantity: 3212.0,
    //     irn_img: null,
    //     irn: "83517da0b7acdec370e8eeb27fe31dfe3921884916ebbb6c0ac16813cd793ca5",
    //     ack_no: "112315087713663",
    //     ack_date: "2023-01-16 10:50:00",
    //     total_amount_in_words:
    //         "Indian Rupee Three Hundred Twelve and Twelve Paise Only.",
    //     total: 600,
    //     notes: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a mauris at nulla pretium hendrerit. Mauris erat neque, vehicula at cursus eget, eleifend ac purus",
    //     terms: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi a mauris at nulla pretium hendrerit. Mauris erat neque, vehicula at cursus eget, eleifend ac purus",
    //     isWatermark: true,
    // };
    const templateHtml = fs.readFileSync(
      path.join(process.cwd(), "invoice.html"),
      "utf8"
    );

    const options = {
      format: "A4",
      headerTemplate: "<p></p>",
      footerTemplate: "<p></p>",
      displayHeaderFooter: false,
      // margin: {
      //     bottom: "64px",
      // },
      printBackground: true,
      path: "invoice.pdf",
    };

    await html_to_pdf({ templateHtml, dataBinding, options });
    const date = new Date();
    console.warn(`Done: invoice.pdf is created at ${date}.`);
  })();
} catch (err) {
  console.log("ERROR:", err);
}
